name: "Update insecure dependencies"

on:
  schedule:
    - cron: 0 8 * * *
jobs:
  update-changelog:
    strategy:
      matrix:
        branch:
          - "release-2.0"
          - "release-1.8"
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub app token
        id: github-app-token
        uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c # v1.7.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: "Clone Kuma"
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - uses: actions/setup-go@v3
        with:
          go-version: "~1.18.9"
      - name: "Install tools"
        run: |
          apt install -y jq git
          GOBIN=/usr/local/bin/ go install github.com/google/osv-scanner/cmd/osv-scanner@v1
      - name: "Update dependencies"
        run: |
          osv-scanner --lockfile=go.mod --json | jq '.results[].packages[].package.name' | xargs -I {} go get -u {}
          go mod tidy
      - name: "Create Pull Request"
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore(deps): security update"
          signoff: true
          branch: chore/security-updates
          delete-branch: true
          title: "chore(deps): security update"
          draft: false
          labels: dependencies
          token: ${{ steps.github-app-token.outputs.token }}
          committer: kumahq[bot] <110050114+kumahq[bot]@users.noreply.github.com>
          author: kumahq[bot] <110050114+kumahq[bot]@users.noreply.github.com>
